# Generated by Django 3.1.5 on 2021-03-02 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210302_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneauth',
            name='phoneNumber',
            field=models.CharField(max_length=150),
        ),
    ]
