# Generated by Django 3.1.7 on 2021-03-30 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='null', max_length=150)),
                ('intro', models.CharField(default='null', max_length=150)),
                ('name', models.CharField(default='null', max_length=150)),
                ('img', models.ImageField(blank=True, null=True, upload_to='image')),
            ],
        ),
        migrations.CreateModel(
            name='Store_BigCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bigCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.bigcategory')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store')),
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='bigcategory',
            field=models.ManyToManyField(through='store.Store_BigCategory', to='category.BigCategory'),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(default='null', max_length=150)),
                ('name', models.CharField(default='null', max_length=150)),
                ('img', models.ImageField(blank=True, null=True, upload_to='food')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='store.store')),
            ],
        ),
    ]
