# Generated by Django 3.1.7 on 2021-04-08 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='intro',
            field=models.TextField(default='null'),
        ),
        migrations.AlterField(
            model_name='store',
            name='location',
            field=models.CharField(default='null', max_length=256),
        ),
    ]
