# Generated by Django 3.1.7 on 2021-04-08 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210408_0350'),
    ]

    sqlCache = []
    reverseSqlCache = []

    categoryStoreList=[
        [1,1],
        [1,2],
        [1,3],
        [1,4],
        [1,5],
        [1,6],
        [1,7],
        [1,8],
        [1,9],
        [1,10],
        [1,11],

        [7,12],
        [7,13],
        [7,14],

        [6,15],
        [6,16],
        [6,17],

        [2,18],
        [2,19],
        [2,20],
    ]

    

    for categoryStore in categoryStoreList:
        sqlCache.append(
            """
                INSERT INTO store_store_bigcategory(bigCategory_id,store_id)
                VALUES('{bigCategory_id}','{store_id}');
            """.format(
                bigCategory_id = categoryStore[0],
                store_id = categoryStore[1]
                )
        )

    reverseSqlCache.append(
        """
            DELETE FROM store_store_bigcategory;
            ALTER TABLE store_store_bigcategory auto_increment=1;
        """
    )

    operations = [
        migrations.RunSQL(
            sql = sqlCache, 
            reverse_sql = reverseSqlCache
        )
    ]
