# Generated by Django 3.1.7 on 2021-04-28 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_auto_20210427_0939'),
        ('store', '0005_auto_20210409_0146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu_SmallCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.menu')),
                ('smallCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.smallcategory')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='smallCategory',
            field=models.ManyToManyField(through='store.Menu_SmallCategory', to='category.SmallCategory'),
        ),
    ]
