# Generated by Django 3.1.7 on 2021-05-15 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210503_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='img',
            field=models.TextField(default='null', null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='img',
            field=models.TextField(default='null', null=True),
        ),
    ]
