# Generated by Django 3.1.7 on 2021-05-16 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BigCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='null', max_length=256)),
                ('img', models.ImageField(blank=True, null=True, upload_to='bigcategory')),
            ],
        ),
        migrations.CreateModel(
            name='SmallCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='null', max_length=256)),
                ('img', models.ImageField(blank=True, null=True, upload_to='smallcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='null', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='SmallCategory_Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smallCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.smallcategory')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.tag')),
            ],
        ),
        migrations.AddField(
            model_name='smallcategory',
            name='tag',
            field=models.ManyToManyField(related_name='smallCategory', through='category.SmallCategory_Tag', to='category.Tag'),
        ),
    ]
