# Generated by Django 3.1.7 on 2021-04-06 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    sqlCache = []
    reverseSqlCache = []

    bigCategoryList=[
        "치킨",
        "분식",
        "일식/돈까스",
        "족발/보쌈",
        "중국집",
        "한식",
        "피자/양식",
        "카페/디저트",
        "야식",
    ]

    for bigCategory in bigCategoryList:
        sqlCache.append(
            """
                INSERT INTO category_bigcategory(name)
                VALUES('{name}');
            """.format(
                name = bigCategory,
                )
        )

    reverseSqlCache.append(
        """
            DELETE FROM category_bigcategory;
            ALTER TABLE category_bigcategory auto_increment=1;
        """
    )


    operations = [
        migrations.RunSQL(
            sql = sqlCache, 
            reverse_sql = reverseSqlCache
        )
    ]
