# Generated by Django 3.1.7 on 2021-05-16 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20210516_0455'),
    ]

    sqlCache = []
    reverseSqlCache = []

    data_list = [
        {"id":1, "name":"\uce58\ud0a8", "img":"smallcategory/chicken.jpg"},
        {"id":2, "name":"\ub2ed\uac15\uc815", "img":"smallcategory/dakkangjeong.jpg"},
        {"id":3, "name":"\ub5a1\ubcf6\uc774", "img":"smallcategory/toppokki-2735719_1920.jpg"},
        {"id":4, "name":"\uae40\ubc25", "img":"smallcategory/kimbab.jpg"},
        {"id":5, "name":"\uc21c\ub300", "img":"smallcategory/sunde.jpg"},
        {"id":6, "name":"\ub9cc\ub450", "img":"smallcategory/mandu.jpg"},
        {"id":7, "name":"\ub77c\uba74", "img":"smallcategory/rameon.jpg"},
        {"id":8, "name":"\ucac4\uba74", "img":"smallcategory/jjolmyeon.jpg"},
        {"id":9, "name":"\ub77c\ubcf6\uc774", "img":"smallcategory/rabok.jpg"},
        {"id":10, "name":"\uad6d\uc218", "img":"smallcategory/noodles.jpg"},
        {"id":11, "name":"\ub3c8\uae4c\uc2a4", "img":"smallcategory/don.jpg"},
        {"id":12, "name":"\ucd08\ubc25", "img":"smallcategory/sushi.jpg"},
        {"id":13, "name":"\uce74\ub808", "img":"smallcategory/curry.jpg"},
        {"id":14, "name":"\ub36e\ubc25", "img":"smallcategory/deop.jpg"},
        {"id":15, "name":"\uc6b0\ub3d9", "img":"smallcategory/udong.jpg"},
        {"id":16, "name":"\uba54\ubc00\uc18c\ubc14", "img":"smallcategory/momil.jpg"},
        {"id":17, "name":"\ud68c", "img":"smallcategory/rawfish.jpg"},
        {"id":18, "name":"\uc624\ucf54\ub178\ubbf8\uc57c\ub07c", "img":"smallcategory/okonomi.jpg"},
        {"id":19, "name":"\ub77c\uba58", "img":"smallcategory/ramen.jpg"},
        {"id":20, "name":"\ud558\uc774\ub77c\uc774\uc2a4", "img":"smallcategory/highrice.jpeg"},
        {"id":21, "name":"\ub098\ubca0", "img":"smallcategory/nabe.jpg"},
        {"id":22, "name":"\ubcf4\uc308", "img":"smallcategory/bossam.jpg"},
        {"id":23, "name":"\uc871\ubc1c", "img":"smallcategory/jokbal.jpg"},
        {"id":24, "name":"\uc9dc\uc7a5\uba74", "img":"smallcategory/jjajangmeon.jpg"},
        {"id":25, "name":"\uc9ec\ubf55", "img":"smallcategory/jambbong.jpg"},
        {"id":26, "name":"\ub9c8\ub77c\ud0d5", "img":"smallcategory/maratang.jpg"},
        {"id":27, "name":"\uc9dc\uc7a5\ubc25", "img":"smallcategory/jjajangbab.jpg"},
        {"id":28, "name":"\ub9c8\ud30c\ub450\ubd80", "img":"smallcategory/mapadubu.jpg"},
        {"id":29, "name":"\ub524\uc12c", "img":"smallcategory/dimsum.jpg"},
        {"id":30, "name":"\ud0d5\uc218\uc721", "img":"smallcategory/tangsu.jpg"},
        {"id":31, "name":"\uae50\ud48d\uae30", "img":"smallcategory/kkanpung.jpg"},
        {"id":32, "name":"\uc720\uc0b0\uc2ac", "img":"smallcategory/yusan.jpg"},
        {"id":33, "name":"\uace0\ucd94\uc7a1\ucc44", "img":"smallcategory/gochujabchae.jpeg"},
        {"id":34, "name":"\uc720\ub9b0\uae30", "img":"smallcategory/yuringi.jpeg"},
        {"id":35, "name":"\uc591\uc7a5\ud53c", "img":"smallcategory/yangjangpi.JPG"},
        {"id":36, "name":"\ub0c9\uba74", "img":"smallcategory/coldnoodles.jpg"},
        {"id":37, "name":"\ub9c8\ub77c\uc0f9\uad88", "img":"smallcategory/marasshang.jpg"},
        {"id":38, "name":"\ube44\ube54\ubc25", "img":"smallcategory/bibimbab.jpg"},
        {"id":39, "name":"\ubcf6\uc74c\ubc25", "img":"smallcategory/bokembab.jpg"},
        {"id":40, "name":"\uad6d\ubc25", "img":"smallcategory/soupbab.jpg"},
        {"id":41, "name":"\ub2ed\ubcf6\uc74c\ud0d5", "img":"smallcategory/dakbokeum.jpg"},
        {"id":42, "name":"\ubd88\uace0\uae30", "img":"smallcategory/bulgogi.jpg"},
        {"id":43, "name":"\uac08\ube44", "img":"smallcategory/galbi.jpg"},
        {"id":44, "name":"\uc0bc\uacb9\uc0b4", "img":"smallcategory/samgyeop.jpg"},
        {"id":45, "name":"\uc81c\uc721", "img":"smallcategory/jeyuk.jpg"},
        {"id":46, "name":"\ub5a1\uac08\ube44", "img":"smallcategory/tteokgalbi.jpg"},
        {"id":47, "name":"\uc0dd\uc120\uad6c\uc774", "img":"smallcategory/fish.jpg"},
        {"id":48, "name":"\uc804", "img":"smallcategory/jeon.jpg"},
        {"id":49, "name":"\uc308\ubc25", "img":"smallcategory/ssambab.jpg"},
        {"id":50, "name":"\ub450\ub8e8\uce58\uae30", "img":"smallcategory/duru.jpg"},
        {"id":51, "name":"\uac8c\uc7a5", "img":"smallcategory/gejang.jpg"},
        {"id":52, "name":"\uc8fd", "img":"smallcategory/juk.jpg"},
        {"id":53, "name":"\uac08\ube44\ucc1c", "img":"smallcategory/galbijjim2.jpg"},
        {"id":54, "name":"\ucc1c\ub2ed", "img":"smallcategory/jjimdak.jpg"},
        {"id":55, "name":"\uac10\uc790\ud0d5", "img":"smallcategory/gamjatang.jpg"},
        {"id":56, "name":"\uc0bc\uacc4\ud0d5", "img":"smallcategory/samgye.jpg"},
        {"id":57, "name":"\uae40\uce58\ucc0c\uac1c", "img":"smallcategory/kimchijjige.png"},
        {"id":58, "name":"\ub41c\uc7a5\ucc0c\uac1c", "img":"smallcategory/doinjangjjige.jpg"},
        {"id":59, "name":"\ubd80\ub300\ucc0c\uac1c", "img":"smallcategory/bude.jpg"},
        {"id":60, "name":"\uc21c\ub450\ubd80\ucc0c\uac1c", "img":"smallcategory/sundubu.JPG"},
        {"id":61, "name":"\uc721\uac1c\uc7a5", "img":"smallcategory/yukge.jpeg"},
        {"id":62, "name":"\uccad\uad6d\uc7a5", "img":"smallcategory/cheongukjang.jpg"},
        {"id":63, "name":"\uc124\ub801\ud0d5", "img":"smallcategory/seoleongtang.jpg"},
        {"id":64, "name":"\ub2ed\uac08\ube44", "img":"smallcategory/dakgalbi.jpg"},
        {"id":65, "name":"\uae40\uce58\ucc1c", "img":"smallcategory/kimchijjim.JPG"},
        {"id":66, "name":"\uc218\uc721", "img":"smallcategory/suyuk.jpg"},
        {"id":67, "name":"\ub3d9\ud30c\uc721", "img":"smallcategory/dongpa.jpg"},
        {"id":68, "name":"\uc544\uadc0\ucc1c", "img":"smallcategory/agui.jpg"},
        {"id":69, "name":"\ubf08\ud574\uc7a5\uad6d", "img":"smallcategory/bbyeo.jpg"},
        {"id":70, "name":"\uc2a4\ud30c\uac8c\ud2f0", "img":"smallcategory/spagetti.jpg"},
        {"id":71, "name":"\ud30c\uc2a4\ud0c0", "img":"smallcategory/pasta.jpg"},
        {"id":72, "name":"\ub9ac\uc870\ub610", "img":"smallcategory/risotto.jpg"},
        {"id":73, "name":"\uc624\ubbc8\ub81b", "img":"smallcategory/omelet.jpg"},
        {"id":74, "name":"\ud53c\uc790", "img":"smallcategory/pizz.jpg"},
        {"id":75, "name":"\uc2a4\ud14c\uc774\ud06c", "img":"smallcategory/stake.jpg"},
        {"id":76, "name":"\ubc14\ubca0\ud050", "img":"smallcategory/grill.jpg"},
        {"id":77, "name":"\uc18c\uc2dc\uc9c0\uad6c\uc774", "img":"smallcategory/sossage.jpg"},
        {"id":78, "name":"\ud544\ub77c\ud504", "img":"smallcategory/pilla.jpg"},
        {"id":79, "name":"\ubc84\uac70", "img":"smallcategory/burger.jpg"},
        {"id":80, "name":"\uc0d0\ub7ec\ub4dc", "img":"smallcategory/salad.jpg"},
        {"id":81, "name":"\uc0cc\ub4dc\uc704\uce58", "img":"smallcategory/sandwich.jpg"},
        {"id":82, "name":"\uacf1\ucc3d", "img":"smallcategory/gob.jpg"},
        {"id":83, "name":"\ub3c4\uc2dc\ub77d", "img":"smallcategory/dosirak.jpg"},
        {"id":84, "name":"\ubd88\ubc31", "img":"smallcategory/bulbaek.jpg"},
        {"id":85, "name":"\ub2ed\ubc1c", "img":"smallcategory/dakbal.jpg"},
        {"id":86, "name":"\ud0c0\ucf54\uc57c\ub07c", "img":"smallcategory/takoyakki.jpg"},
        {"id":87, "name":"\uc624\ub3cc\ubf08", "img":"smallcategory/odol.jpg"},
        {"id":88, "name":"\ub9c9\ucc3d", "img":"smallcategory/makchang.jpg"},
        {"id":89, "name":"\uc300\uad6d\uc218", "img":"smallcategory/ricenoodles.jpg"},
        {"id":90, "name":"\ube0c\ub9ac\ub610", "img":"smallcategory/buritto.jpg"},
        {"id":91, "name":"\ud0c0\ucf54", "img":"smallcategory/taco.jpg"},
        {"id":92, "name":"\ud31f\ud0c0\uc774", "img":"smallcategory/pottai.jpg"}
    ]

    for data in data_list:
        sqlCache.append(
            """
                INSERT INTO category_smallcategory(`id`, `name`, `img`)
                VALUES('{id}', '{name}', '{img}')
            """.format(
                id = data["id"],
                name = data["name"],
                img = data["img"]
                )
        )

    reverseSqlCache.append(
        """
            DELETE FROM category_smallcategory;
            ALTER TABLE category_smallcategory auto_increment=1;
        """
    )

    operations = [
        migrations.RunSQL(
            sql = sqlCache,
            reverse_sql = reverseSqlCache
        )
    ]


