# Generated by Django 3.1.7 on 2021-04-04 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_add_bigcategory_data'),
    ]

    sqlCache = []
    reverseSqlCache = []

    smallCategoryList=[
        ["치킨",1],
        ["닭강정",1],
        ["떡볶이",2],
        ["김밥",2],
        ["순대",2],
        ["만두",2],
        ["라면",2],
        ["쫄면",2],
        ["라볶이",2],
        ["국수",2],
        ["돈까스",3],
        ["초밥",3],
        ["카레",3],
        ["덮밥",3],
        ["우동",3],
        ["메밀소바",3],
        ["회",3],
        ["오코노미야끼",3],
        ["라멘",3],
        ["하이라이스",3],
        ["나베",3],
        ["보쌈",4],
        ["족발",4],
        ["짜장면",5],
        ["짬뽕",5],
        ["마라탕",5],
        ["짜장볶음밥",5],
        ["마파두부",5],
        ["딤섬",5],
        ["탕수육",5],
        ["깐풍기",5],
        ["유산슬",5],
        ["고추잡채",5],
        ["유린기",5],
        ["양장피",5],
        ["냉면",5],
        ["마라샹궈",5],
        ["비빔밥",6],
        ["볶음밥",6],
        ["국밥",6],
        ["닭볶음탕",6],
        ["불고기",6],
        ["갈비",6],
        ["삼겹살",6],
        ["제육",6],
        ["떡갈비",6],
        ["생선구이",6],
        ["전",6],
        ["쌈밥",6],
        ["두루치기",6],
        ["게장",6],
        ["죽",6],
        ["갈비찜",6],
        ["찜닭",6],
        ["감자탕",6],
        ["삼계탕",6],
        ["김치찌개",6],
        ["된장찌개",6],
        ["부대찌개",6],
        ["순두부찌개",6],
        ["육개장",6],
        ["청국장",6],
        ["설렁탕",6],
        ["닭갈비",6],
        ["김치찜",6],
        ["수육",6],
        ["동파육",6],
        ["아귀찜",6],
        ["뼈해장국",6],
        ["스파게티",7],
        ["파스타",7],
        ["리조또",7],
        ["오믈렛",7],
        ["피자",7],
        ["스테이크",7],
        ["그릴바베큐",7],
        ["소시지구이",7],
        ["필라프",7],
        ["버거",7],
        ["샐러드",8],
        ["샌드위치",8],
        ["곱창",9],
        ["도시락",9],
        ["불백",9],
        ["닭발",9],
        ["타코야끼",9],
        ["오돌뼈",9],
        ["막창",9],
        ["쌀국수",9],
        ["브리또",9],
        ["타코",9],
        ["팟타이",9]
    ]

    

    for smallCategory in smallCategoryList:
        sqlCache.append(
            """
                INSERT INTO category_smallcategory(name,bigCategory_id)
                VALUES('{name}','{bigCategory_id}');
            """.format(
                name = smallCategory[0],
                bigCategory_id = smallCategory[1]
                )
        )

    reverseSqlCache.append(
        """
            DELETE FROM category_smallcategory;
            ALTER TABLE category_smallcategory auto_increment=1;
        """
    )

    operations = [
        migrations.RunSQL(
            sql = sqlCache, 
            reverse_sql = reverseSqlCache
        )
    ]
