# Generated by Django 3.1.7 on 2021-04-06 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_add_bigcategory_data'),
    ]

    sqlCache = []
    reverseSqlCache = []

    smallCategoryList=[
        ["치킨",1],
        ["닭강정",1],
        ["버거",2],
        ["갈비찜",3],
        ["찜닭",3],
        ["감자탕",3],
        ["삼계탕",3],
        ["김치찌개",3],
        ["된장찌개",3],
        ["부대찌개",3],
        ["순두부찌개",3],
        ["육개장",3],
        ["청국장",3],
        ["설렁탕",3],
        ["닭갈비",3],
        ["김치찜",3],
        ["수육",3],
        ["동파육",3],
        ["아귀찜",3],
        ["뼈해장국",3],
        ["떡볶이",4],
        ["김밥",4],
        ["순대",4],
        ["만두",4],
        ["라면",4],
        ["쫄면",4],
        ["라볶이",4],
        ["국수",4],
        ["돈까스",5],
        ["초밥",5],
        ["카레",5],
        ["덮밥",5],
        ["우동",5],
        ["메밀소바",5],
        ["회",5],
        ["오코노미야끼",5],
        ["라멘",5],
        ["하이라이스",5],
        ["나베",5],
        ["보쌈",6],
        ["족발",6],
        ["짜장면",7],
        ["짬뽕",7],
        ["마라탕",7],
        ["짜장볶음밥",7],
        ["마파두부",7],
        ["딤섬",7],
        ["탕수육",7],
        ["깐풍기",7],
        ["유산슬",7],
        ["고추잡채",7],
        ["유린기",7],
        ["양장피",7],
        ["냉면",7],
        ["마라샹궈",7],
        ["비빔밥",8],
        ["볶음밥",8],
        ["국밥",8],
        ["닭볶음탕",8],
        ["불고기",8],
        ["갈비",8],
        ["삼겹살",8],
        ["제육",8],
        ["떡갈비",8],
        ["생선구이",8],
        ["전",8],
        ["쌈밥",8],
        ["두루치기",8],
        ["게장",8],
        ["죽",8],
        ["스파게티",9],
        ["파스타",9],
        ["리조또",9],
        ["오믈렛",9],
        ["피자",9],
        ["스테이크",9],
        ["그릴바베큐",9],
        ["소시지구이",9],
        ["필라프",9],
        ["샐러드",10],
        ["샌드위치",10],
        ["곱창",11],
        ["도시락",11],
        ["불백",11],
        ["닭발",11],
        ["타코야끼",11],
        ["오돌뼈",11],
        ["막창",11],
        ["쌀국수",11],
        ["브리또",11],
        ["타코",11],
        ["팟타이",11]
    ]

    

    for smallCategory in smallCategoryList:
        sqlCache.append(
            """
                INSERT INTO category_smallcategory(name,bigCategory_id)
                VALUES('{name}','{bigCategory_id}');
            """.format(
                name = smallCategory[0],
                bigCategory_id = smallCategory[1]
                )
        )

    reverseSqlCache.append(
        """
            DELETE FROM category_smallcategory;
            ALTER TABLE category_smallcategory auto_increment=1;
        """
    )

    operations = [
        migrations.RunSQL(
            sql = sqlCache, 
            reverse_sql = reverseSqlCache
        )
    ]
