# Generated by Django 3.1.7 on 2021-04-12 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_add_smallcategory_data'),
    ]

    operations = [
        migrations.RunSQL(
            sql = "UPDATE category_smallcategory SET name = '짜장밥' WHERE id = 27; UPDATE category_smallcategory SET name = '바베큐' WHERE id = 76; ", 
            reverse_sql = "SELECT * FROM category_smallcategory WHERE id < 1"
        )
    ]
