# Generated by Django 3.1.7 on 2021-04-27 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_auto_20210412_0929'),
    ]

    operations = [
        migrations.RunSQL(
            sql =  "UPDATE category_smallcategory SET img = 'null' WHERE id<100;" , 
            reverse_sql = "UPDATE category_smallcategory SET img = null WHERE id<100;"
        )
    ]
