# Generated by Django 3.1.7 on 2021-04-29 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_auto_20210427_0939'),
    ]

    sqlCache = []
    reverseSqlCache = []

    tagList=[ "닭고기", "돼지고기", "소고기", "김치", "된장", "햄", "두부", "생선", "떡", "밥", "면", "튀김", "갑각류", "채소" ,"한식", "찜", "탕", "분식", "일식", "양식", "중국", "아시안", "패스트푸드", "야식","빵"]

    for tag in tagList:
        sqlCache.append(
            """
                INSERT INTO category_tag(name)
                VALUES('{name}');
            """.format(
                name = tag,
                )
        )

    reverseSqlCache.append(
        """
            DELETE FROM category_tag;
            ALTER TABLE category_tag auto_increment=1;
        """
    )


    operations = [
        migrations.RunSQL(
            sql = sqlCache, 
            reverse_sql = reverseSqlCache
        )
    ]
