# Generated by Django 3.1.7 on 2021-05-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_auto_20210429_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigcategory',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='bigcategory'),
        ),
        migrations.AlterField(
            model_name='smallcategory',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='smallcategory'),
        ),
    ]
