# Generated by Django 3.1.7 on 2021-05-14 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0009_auto_20210513_2147'),
    ]

    imgList = [
        'chicken.jpg',
        'dakkangjeong.jpg',
        'toppokki-2735719_1920.jpg',
        'kimbab.jpg',
        'sunde.jpg',
        'mandu.jpg',
        'rameon.jpg',
        'jjolmyeon.jpg',
        'rabok.jpg',
        'noodles.jpg',
        'don.jpg',
        'sushi.jpg',
        'curry.jpg',
        'deop.jpg',
        'udong.jpg',
        'momil.jpg',
        'rawfish.jpg',
        'okonomi.jpg',
        'ramen.jpg',
        'highrice.jpeg',
        'nabe.jpg',
        'bossam.jpg',
        'jokbal.jpg',
        'jjajangmeon.jpg',
        'jambbong.jpg',
        'maratang.jpg',
        'jjajangbab.jpg',
        'mapadubu.jpg',
        'dimsum.jpg',
        'tangsu.jpg',
        'kkanpung.jpg',
        'yusan.jpg',
        'gochujabchae.jpeg',
        'yuringi.jpeg',
        'yangjangpi.JPG',
        'coldnoodles.jpg',
        'marasshang.jpg',
        'bibimbab.jpg',
        'bokembab.jpg',
        'soupbab.jpg',
        'dakbokeum.jpg',
        'bulgogi.jpg',
        'galbi.jpg',
        'samgyeop.jpg',
        'jeyuk.jpg',
        'tteokgalbi.jpg',
        'fish.jpg',
        'jeon.jpg',
        'ssambab.jpg',
        'duru.jpg',
        'gejang.jpg',
        'juk.jpg',
        'galbijjim2.jpg',
        'jjimdak.jpg',
        'gamjatang.jpg',
        'samgye.jpg',
        'kimchijjige.png',
        'doinjangjjige.jpg',
        'bude.jpg',
        'sundubu.JPG',
        'yukge.jpeg',
        'cheongukjang.jpg',
        'seoleongtang.jpg',
        'dakgalbi.jpg',
        'kimchijjim.JPG',
        'suyuk.jpg',
        'dongpa.jpg',
        'agui.jpg',
        'bbyeo.jpg',
        'spagetti.jpg',
        'pasta.jpg',
        'risotto.jpg',
        'omelet.jpg',
        'pizz.jpg',
        'stake.jpg',
        'grill.jpg',
        'sossage.jpg',
        'pilla.jpg',
        'burger.jpg',
        'salad.jpg',
        'sandwich.jpg',
        'gob.jpg',
        'dosirak.jpg',
        'bulbaek.jpg',
        'dakbal.jpg',
        'takoyakki.jpg',
        'odol.jpg',
        'makchang.jpg',
        'ricenoodles.jpg',
        'buritto.jpg',
        'taco.jpg',
        'pottai.jpg'
    ]


    sqlCache = []
    for i, img in enumerate(imgList):
        sqlCache.append(
            """
                UPDATE category_smallcategory
                SET img = 'smallcategory/{img}'
                WHERE id = {i};
            """.format(img = img, i = i+1)
        )

    reverseSqlCache = []
    reverseSqlCache.append(
        """
            UPDATE category_smallcategory
            SET img = null
            where id>=1;
        """
    )


    operations = [
        migrations.RunSQL(
            sql = sqlCache,
            reverse_sql = reverseSqlCache
        )
    ]
