# Generated by Django 3.1.7 on 2021-03-30 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='taste',
            field=models.IntegerField(null=True),
        ),
    ]
