# Generated by Django 3.1.7 on 2021-04-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210330_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='amount',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='user',
            name='price',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='user',
            name='taste',
            field=models.IntegerField(default=-1),
        ),
    ]
