# Generated by Django 3.1.7 on 2021-05-23 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210516_0527'),
    ]

    data_list = [
        {"id":1, "timestamp":"2021-05-18 07:15:01.435305", "timeSlot":"morning", "weather":"Rain, \uc801\uc815", "user_id":1},
        {"id":2, "timestamp":"2021-05-18 07:15:01.435305", "timeSlot":"morning", "weather":"Snow, \uc801\uc815", "user_id":1},
        {"id":3, "timestamp":"2021-05-18 11:15:01.435305", "timeSlot":"lunch", "weather":"Clear, \uc801\uc815", "user_id":1},
        {"id":4, "timestamp":"2021-05-18 11:15:01.435305", "timeSlot":"lunch", "weather":"Clouds, \uc801\uc815", "user_id":1},
        {"id":5, "timestamp":"2021-05-18 16:15:01.435305", "timeSlot":"latelunch", "weather":"Rain, \ub354\uc6c0", "user_id":1},
        {"id":6, "timestamp":"2021-05-18 16:15:01.435305", "timeSlot":"latelunch", "weather":"Snow, \ub354\uc6c0", "user_id":1},
        {"id":7, "timestamp":"2021-05-18 19:15:01.435305", "timeSlot":"dinner", "weather":"Clear, \ub354\uc6c0", "user_id":1},
        {"id":8, "timestamp":"2021-05-18 19:15:01.435305", "timeSlot":"dinner", "weather":"Clouds, \ub354\uc6c0", "user_id":1},
        {"id":9, "timestamp":"2021-05-18 22:15:01.435305", "timeSlot":"midnightsnack", "weather":"Rain, \ucd94\uc6c0", "user_id":1},
        {"id":10, "timestamp":"2021-05-18 22:15:01.435305", "timeSlot":"midnightsnack", "weather":"Snow, \ucd94\uc6c0", "user_id":1},
        {"id":11, "timestamp":"2021-05-18 20:15:01.435305", "timeSlot":"dinner", "weather":"Clear, \ucd94\uc6c0", "user_id":1},
        {"id":12, "timestamp":"2021-05-18 20:15:01.435305", "timeSlot":"dinner", "weather":"Clouds, \ucd94\uc6c0", "user_id":1}
        ]

    sqlCache = []
    for data in data_list:
        sqlCache.append(
            """
                INSERT INTO account_order(`id`, `timestamp`,`timeSlot`,`weather`, `user_id`)
                VALUES('{id}', '{timestamp}', '{timeSlot}','{weather}','{user_id}')
                ON DUPLICATE KEY UPDATE timestamp = '{timestamp}', timeSlot = '{timeSlot}', weather = '{weather}', user_id = '{user_id}'
            """.format(
                id = data["id"],
                timestamp = data["timestamp"],
                timeSlot = data["timeSlot"],
                weather = data["weather"],
                user_id = data["user_id"]
                )
        )

    reverseSqlCache = []
    reverseSqlCache.append(
        """
            DELETE FROM account_order;
            ALTER TABLE account_order auto_increment=1;
        """
    )

    operations = [
        migrations.RunSQL(
            sql = sqlCache,
            reverse_sql = reverseSqlCache
        )
    ]