# Generated by Django 3.1.7 on 2021-05-23 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210523_1324'),
        ('store', '0004_auto_20210519_1416')
    ]

    data_list = [
        {"id":2, "menu_id":24, "order_id":1},
        {"id":3, "menu_id":25, "order_id":1},
        {"id":4, "menu_id":36, "order_id":1},
        {"id":6, "menu_id":24, "order_id":1},
        {"id":7, "menu_id":25, "order_id":1},
        {"id":8, "menu_id":36, "order_id":1},
        {"id":9, "menu_id":57, "order_id":1},
        {"id":10, "menu_id":11, "order_id":3},
        {"id":11, "menu_id":2, "order_id":3},
        {"id":12, "menu_id":3, "order_id":3},
        {"id":13, "menu_id":14, "order_id":3},
        {"id":14, "menu_id":24, "order_id":3},
        {"id":15, "menu_id":25, "order_id":3},
        {"id":16, "menu_id":79, "order_id":5},
        {"id":17, "menu_id":5, "order_id":5},
        {"id":18, "menu_id":2, "order_id":5},
        {"id":19, "menu_id":3, "order_id":5},
        {"id":20, "menu_id":2, "order_id":5},
        {"id":21, "menu_id":1, "order_id":7},
        {"id":22, "menu_id":23, "order_id":7},
        {"id":23, "menu_id":54, "order_id":7},
        {"id":24, "menu_id":22, "order_id":7},
        {"id":25, "menu_id":1, "order_id":9},
        {"id":26, "menu_id":85, "order_id":9},
        {"id":27, "menu_id":82, "order_id":9},
        {"id":28, "menu_id":17, "order_id":9},
        {"id":29, "menu_id":1, "order_id":9},
        {"id":31, "menu_id":24, "order_id":1},
        {"id":32, "menu_id":25, "order_id":1},
        {"id":33, "menu_id":36, "order_id":1},
        {"id":34, "menu_id":57, "order_id":1},
        {"id":35, "menu_id":11, "order_id":3},
        {"id":36, "menu_id":2, "order_id":3},
        {"id":37, "menu_id":3, "order_id":3},
        {"id":38, "menu_id":14, "order_id":3},
        {"id":39, "menu_id":24, "order_id":3},
        {"id":40, "menu_id":25, "order_id":3},
        {"id":41, "menu_id":79, "order_id":5},
        {"id":42, "menu_id":5, "order_id":5},
        {"id":43, "menu_id":2, "order_id":5},
        {"id":44, "menu_id":3, "order_id":5},
        {"id":45, "menu_id":2, "order_id":5},
        {"id":46, "menu_id":1, "order_id":7},
        {"id":47, "menu_id":23, "order_id":7},
        {"id":48, "menu_id":54, "order_id":7},
        {"id":49, "menu_id":22, "order_id":7},
        {"id":50, "menu_id":1, "order_id":9},
        {"id":51, "menu_id":85, "order_id":9},
        {"id":52, "menu_id":82, "order_id":9},
        {"id":53, "menu_id":17, "order_id":9},
        {"id":54, "menu_id":1, "order_id":9},
        {"id":55, "menu_id":54, "order_id":1},
        {"id":56, "menu_id":56, "order_id":1},
        {"id":58, "menu_id":408, "order_id":1},
        {"id":59, "menu_id":1326, "order_id":1},
        {"id":60, "menu_id":225, "order_id":1},
        {"id":61, "menu_id":418, "order_id":1},
        {"id":62, "menu_id":89, "order_id":1},
        {"id":63, "menu_id":64, "order_id":3},
        {"id":64, "menu_id":78, "order_id":3},
        {"id":65, "menu_id":25, "order_id":3},
        {"id":66, "menu_id":4, "order_id":3},
        {"id":67, "menu_id":408, "order_id":3},
        {"id":68, "menu_id":1326, "order_id":3},
        {"id":69, "menu_id":4669, "order_id":5},
        {"id":70, "menu_id":15, "order_id":5},
        {"id":71, "menu_id":78, "order_id":5},
        {"id":72, "menu_id":25, "order_id":5},
        {"id":73, "menu_id":381, "order_id":5},
        {"id":74, "menu_id":6127, "order_id":7},
        {"id":75, "menu_id":2186, "order_id":7},
        {"id":76, "menu_id":1142, "order_id":7},
        {"id":77, "menu_id":261, "order_id":7},
        {"id":78, "menu_id":6127, "order_id":9},
        {"id":79, "menu_id":350, "order_id":9},
        {"id":80, "menu_id":1457, "order_id":9},
        {"id":81, "menu_id":1369, "order_id":9},
        {"id":82, "menu_id":6127, "order_id":9},
        {"id":83, "menu_id":229, "order_id":1},
        {"id":84, "menu_id":1142, "order_id":1},
        {"id":85, "menu_id":7572, "order_id":1},
        {"id":86, "menu_id":10862, "order_id":1},
        {"id":87, "menu_id":1326, "order_id":1},
        {"id":88, "menu_id":1459, "order_id":1},
        {"id":89, "menu_id":396, "order_id":1},
        {"id":90, "menu_id":82, "order_id":1},
        {"id":91, "menu_id":172, "order_id":2},
        {"id":92, "menu_id":50, "order_id":2},
        {"id":93, "menu_id":9318, "order_id":2},
        {"id":94, "menu_id":8357, "order_id":2},
        {"id":95, "menu_id":964, "order_id":2},
        {"id":96, "menu_id":1357, "order_id":2},
        {"id":97, "menu_id":2071, "order_id":2},
        {"id":98, "menu_id":50, "order_id":3},
        {"id":99, "menu_id":9318, "order_id":3},
        {"id":100, "menu_id":381, "order_id":3},
        {"id":101, "menu_id":564, "order_id":3},
        {"id":102, "menu_id":25, "order_id":3}
    ]


    sqlCache = []
    for data in data_list:
        sqlCache.append(
            """
                INSERT INTO account_order_menu(`id`, `menu_id`,`order_id`)
                VALUES('{id}', '{menu_id}', '{order_id}')
                ON DUPLICATE KEY UPDATE menu_id = '{menu_id}', order_id = '{order_id}';
            """.format(
                id = data["id"],
                menu_id = data["menu_id"],
                order_id = data["order_id"],
                )
        )

    reverseSqlCache = []
    reverseSqlCache.append(
        """
            DELETE FROM account_order_menu;
            ALTER TABLE account_order_menu auto_increment=1;
        """
    )

    operations = [
        migrations.RunSQL(
            sql = sqlCache,
            reverse_sql = reverseSqlCache
        )
    ]