# Generated by Django 3.1.7 on 2021-05-03 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_menu',
            name='timeSlot',
            field=models.CharField(choices=[('morning', 'morning'), ('lunch', 'lunch'), ('latelunch', 'latelunch'), ('dinner', 'dinner'), ('midnignsnack', 'midnignsnack')], default='null', max_length=150),
        ),
    ]
