# Generated by Django 3.1.7 on 2021-05-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20210503_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_smallcategory',
            old_name='eventCount',
            new_name='eventValue',
        ),
        migrations.AlterField(
            model_name='user_smallcategory',
            name='eventType',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user_smallcategory',
            name='timestamp',
            field=models.IntegerField(default=0),
        ),
    ]
