# Generated by Django 3.1.7 on 2021-05-04 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_auto_20210429_1322'),
        ('account', '0011_user_smallcategory_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_SmallCategory_Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('smallCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.smallcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='User_SmallCategory',
        ),
        migrations.AlterField(
            model_name='user',
            name='userSmallCategory',
            field=models.ManyToManyField(through='account.User_SmallCategory_Like', to='category.SmallCategory'),
        ),
    ]
