# Generated by Django 3.1.7 on 2021-05-05 00:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_auto_20210429_1322'),
        ('account', '0012_auto_20210504_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userSmallCategory',
        ),
        migrations.CreateModel(
            name='User_SmallCategory_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('smallCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.smallcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
