# Generated by Django 3.1.7 on 2021-05-10 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20210509_0128'),
        ('account', '0016_auto_20210508_1654'),
    ]

    operations = [
    ]
