# Generated by Django 3.1.7 on 2021-05-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20210510_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='timeSlot',
            field=models.CharField(choices=[('morning', 'morning'), ('lunch', 'lunch'), ('latelunch', 'latelunch'), ('dinner', 'dinner'), ('midnigtsnack', 'midnigntsnack')], default='null', max_length=150),
        ),
    ]
