# Generated by Django 3.1.7 on 2021-05-13 07:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_auto_20210511_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_smallcategory_feedback',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
    ]
