# Generated by Django 3.1.7 on 2021-05-13 07:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_auto_20210513_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_smallcategory_feedback',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
