# Generated by Django 3.1.5 on 2021-03-02 00:34

import apps.koreantranlater.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KoreanTranslaterRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='default')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('photo', models.FileField(upload_to=apps.koreantranlater.models.translate_request_filename)),
            ],
        ),
    ]
